Vagrant.configure("2") do |config|
    config.vm.provider "docker" do |d|
      d.image = "ubuntu-vagrant:22.04"
      d.has_ssh = true
      d.remains_running = true
      d.create_args = ["--privileged"]
    end
    config.ssh.private_key_path = "insecure_vagrant_docker_id"
    config.vm.network "forwarded_port", id: "ssh", host: 2222, guest: 22
  end